name: Release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version-and-release:
    name: Version and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写入仓库的权限
      packages: write  # 发布 npm 包需要的权限
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # 明确指定使用 GITHUB_TOKEN

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup npmrc
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install

      - name: Run changeset version
        run: pnpm changeset:version

      - name: Commit version changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "chore: update versions [skip ci]"
          git push

      - name: Reinstall dependencies
        run: pnpm install

      - name: Debug Tokens
        run: |
          echo "NPM_USER: $(npm whoami)"
          echo "REGISTRY: $(npm config get registry)"

      - name: Publish packages
        run: pnpm release --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
